version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181" # Host:Container (or just Container)
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost # Do not use localhost or 127.0.0.1 if you want to run multiple brokers
      KAFKA_CREATE_TOPICS: "audit-logging:1:1" # 1 partition and 1 replica
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  audit-log-app:
    restart: always
    build: . # current directory contains a Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/usr/src/app/logs # to persist log files
    depends_on:
      - kafka
      - mongo
    networks:
      - backend
  mongo:
    image: mongo
    volumes: 
      - /var/lib/mongodb:/var/lib/mongodb # persistent storage
    ports:
      - "27017:27017"
    networks:
      - backend
  networks:
    - backend

